---
title: "VN-CDC Covid-19 dashboard data"
output:
  html_document:
    theme: cerulean
    toc: yes
  pdf_document:
    toc: yes
editor_options: 
  chunk_output_type: console
---

```{css, echo=FALSE}
pre, code {white-space:pre !important; overflow-x:auto}
```

```{r general options, include = FALSE}
knitr::knit_hooks$set(
  margin = function(before, options, envir) {
    if (before) par(mgp = c(1.5, .5, 0), bty = "n", plt = c(.105, .97, .13, .97))
    else NULL
  },
  prompt = function(before, options, envir) {
    options(prompt = if (options$engine %in% c("sh", "bash")) "$ " else "> ")
  })

knitr::opts_chunk$set(margin = TRUE, message = FALSE, warning = FALSE,
                      prompt = FALSE, comment = "##", collapse = FALSE,
                      cache = FALSE, autodep = TRUE,
                      dev.args = list(pointsize = 11), fig.height = 3.5,
                      fig.width = 4.24725, fig.retina = 2, fig.align = "center")

options(width = 263)

l <- "en_US.UTF-8"
Sys.setenv(LANGAGE = l)
Sys.setlocale(locale = l)
Sys.setlocale("LC_MESSAGES", l)
```

```{r}
library(magrittr)
library(readxl)
library(dplyr)
```

## Data cleaning

```{r}
file <- "../raw data/file ca xam nhap + ca thu cap-2.xlsx"
```

A function that converts dates, accounting for the fact that 2 formats are mixed
in the same vector...

```{r}
convert_dates <- function(x) {
  as.Date(ifelse(grepl("/", x),
                 as.Date(x, "%d/%m/%y"),
                 as.Date(as.numeric(x), origin = "1899-12-30")),
          origin = "1970-01-01")
}                 
```

```{r}
fix_dates <- function(x, m = 4) {
  as.Date(ifelse((lubridate::month(x) > m & lubridate::day(x) == m) | x < x[1],
                 lubridate::ydm(x), x),
          origin = "1970-01-01")
}
```

Imported cases:

```{r}
imported <- read_excel(file, " xam nhap") %>%
  select(`Mã BN`, `Ngày xét nhiệm`, Code) %>% 
  setNames(c("ID", "date", "code")) %>% 
  mutate(date = fix_dates(convert_dates(date)))
```

Origin of cases:

```{r}
origin <- read_excel(file, "Sheet4") %>% 
  select("Ngày", "Ca lây nhiễm từ ca xâm nhập", "Ca dương tính sau khi cách ly",
         "Ca thứ phát lây tại cộng đồng", "Ca xâm nhập phát hiện sau khi nhập cảnh") %>% 
  setNames(c("date", "at_entry", "isolation", "community", "after_entry")) %>% 
  mutate(date = lubridate::mdy(date, locale = "en_US.UTF-8")) %>% 
  mutate_if(is.numeric, as.integer)
```

Community transmission:

```{r}
community <- read_excel(file, "thu cap") %>% 
  select("Mã BN", "Ngày xét nhiệm", "Code") %>%
  setNames(c("ID", "date", "code")) %>% 
  mutate(date = fix_dates(convert_dates(date)))
```

Isolations:

```{r}
isolation <- read_excel("../raw data/Vietnam interventions.xlsx", skip = 1) %>% 
  mutate_at("date", as.Date) %>% 
  arrange(date)
```

```{r}
isolation_vncdc <- isolation %>% 
  select("date", "quarantine in health facilities",
         "quarantine at home or hotel", "quarantine in quarantine stay") %>% 
  setNames(c("date", "health_facility", "home", "quarantine")) %>% 
  na.exclude()
```

### Writing to disk

```{r}
write.csv3 <- function(...) write.csv2(..., quote = FALSE, row.names = FALSE)
write.csv3(origin, "../clean data/origin.csv")
write.csv3(imported, "../clean data/imported.csv")
write.csv3(community, "../clean data/community.csv")
write.csv3(isolation_vncdc, "../clean data/isolation_vncdc.csv")
saveRDS(origin, "../clean data/origin.rds")
saveRDS(imported, "../clean data/imported.rds")
saveRDS(community, "../clean data/community.rds")
saveRDS(isolation_vncdc, "../clean data/isolation_vncdc.rds")
```

## Data quick vizualization

```{r}
sum(tail(origin, 1)[, -1])
```

```{r}
nrow(imported)
```

```{r}
nrow(community)
```

```{r}
nrow(imported) + nrow(community)
```

```{r fig.width = 2 * 4.24725}
colors <- c(`at entry` = "#e41a1c",
            `from isolation` = "#377eb8",
            `after entry` = "#4daf4a",
            `community transmission` = "#984ea3")
xlim <- range(origin$date)
lwd <- 2
origin %>% 
  mutate(total = at_entry + isolation + community + after_entry) %>%
  with({
    plot(date, total, type = "s", lwd = lwd, xlim = xlim,
         xlab = NA, ylab = "cumulative number of confirmed cases")
    lines(date, at_entry, type = "s", lwd = lwd, col = colors[1])
    lines(date, isolation, type = "s", lwd = lwd, col = colors[2])
    lines(date, after_entry, type = "s", lwd = lwd, col = colors[3])
    lines(date, community, type = "s", lwd = lwd, col = colors[4])
  })
legend("topleft", legend = c("total", names(colors)), col = c("black", colors), lwd = lwd, bty = "n")

```

```{r}
rep_x <- function(x) {
  rep(c(x, tail(x, 1) + 1), each = 2)
}
```

```{r}
rep_y <- function(y) {
  c(0, rep(y, each = 2), 0)
}
```

```{r fig.width = 2 * 4.24725, fig.height = .65 * 3.5}
col <- c(`home: low-risk foreign countries` = "#1b9e77", `quarantine: high-risk area, F1, some F2` = "#7570b3", `health facility: symptoms with F1 or high-risk area` = "#d95f02")
col_fill <- adjustcolor(col, .5)
with(isolation_vncdc, {
 plot(date, home, type = "n", xlim = xlim, ylim = c(max(home), 0), lwd = lwd, col = colors[1], axes = FALSE, xlab = NA, ylab = "number of people isolated")
 polygon(rep_x(date), rep_y(home), col = col_fill[1], border = col[1], lwd = lwd)
 polygon(rep_x(date - .5), rep_y(quarantine), col = col_fill[2], border = col[2], lwd = lwd)
 polygon(rep_x(date + .5), rep_y(health_facility), col = col_fill[3], border = col[3], lwd = lwd)
 axis(2)
 axis(3, as.numeric(lubridate::ymd(c("2020-02-01", "2020-03-01", "2020-04-01"))))
})
legend("topleft", legend = rev(names(col)), fill = rev(col_fill), border = rev(col), bty = "n")
```

